### ISSUE TITLE
Error during the calculation with dimer benzene

### ISSUE THREAD

**Issue by sli259** [hema-ted/pycdft#3]
Hi, I am trying to use the code and test on a benzene dimer, I run into the error during coupling calculation. 

assert wfc1.nspin == wfc2.nspin
AttributeError: ‘NoneType’ object has no attribute ‘nspin’

I compared my input files with those in the thiophene and couldn’t find what is the problem. Can you give me some suggestions about what I missed?

Thanks!
Here are my inputs for the coupling calculation. 
[benz.zip](https://github.com/hema-ted/pycdft/files/5496504/benz.zip)

I am trying to run this in the interactive mode and then run the python code line by line to find out the problem. At the step solver1.solve() I got following errors:

~~~~~~~~~~~~~~~~~~~~ Applying CDFT ~~~~~~~~~~~~~~~~~~~~
---- solver A ------
===================== Initializing Run =====================
(<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <trace
back object at 0x7f5d20f1cb40>)
Terminating DFT driver...

**Comment by wwwennie** [comment]
Hello, we apologize for the delayed response. For also the benefit of future users, our response is below.
---------
Based on the input files provided, the first place to check would be to make sure you provide pycdft a structure file with lattice parameters; the easiest way to do this would be to use *cif file instead of an *xyz in
