### ISSUE TITLE
Can pycdft method be applied into the systems where the acceptor and donor fragments are different?

### ISSUE THREAD

**Issue by Fly330** [hema-ted/pycdft#4]
Dear Experts,
My research focuses on the simulation of charge transfer processes in solid-liquid interfaces. Recently, I read your excellent paper “PyCDFT: A Python package for constrained density functional theory”, and plan to apply cDFT method into the calculation of outer-sphere reaction rate of organic carbonates on the electrodes.
I have successfully compiled the qbox and pycdft codes, run the example cases, and obtained the same results as demo output files. However, I find that the molecule of acceptor part is the same as donor’s in all cases (He-He+ dimer and thiophene-thiophene+ dimer). **Can pycdft method be applied into the systems where the acceptor and donor fragments are different?** Additionally, **how to set up the parameters in pycdft to achieve the structural optimization with constraint potential?** I don’t find the detailed parameter introduction in the pycdft package. **Could you please share me a formal manual file of pycdft (my Email address is fangyuan@fudan.edu.cn)?** Many thanks!

Best Regards,
Yuan Fang

**Comment by wwwennie** [comment]
Hello Yuan, thanks for your interest in pycdft. In answer to your questions

1. Can pycdft method be applied into the systems where the acceptor and donor fragments are different? 
Yes, it is possible to define acceptor and donor fragments that are different from each other. The example cases were chosen so that we could compare to known literature values from previous codes. In your case of interest (organic carbonates on electrodes), things are much more complex and may require some thought about the physics of the system itself; at the very least, you may need to rely on your physical intuition to choose the acceptor and donor fragments and try several configurations. I recommend to also check the constrained charge density as part of this.  

2. Additionally, how to set up the parameters in pycdft to achieve the structural optimization with constraint potential? 
pycdft has forces due to the constraint potential implemented and these are fed into qbox, so it would be possible to do structural optimization with a constraint potential. It is largely a matter of passing the desired commands to qbox. The following parameters would be of interest to you:

- QboxDriver: you'll need to modify the `init_cmd` with commands passed onto qbox, e.g., with the choice of atomic dynamics (`atoms_dyn`) and instead of `scf_cmd`, set `opt_cmd` to something where the first number passed to the `run` command is non-zero (see the Qbox documentation for more info). There is an example of structural optimization in the qbox documentation as well. 
- CDFTSolver: change` job="scf"` to `job="opt"`

See also `extforce` and `run` command in the Qbox documentation (http://qboxcode.org/doc/html/).
The restart functionality (as shown in the `01_he_coupling tutorial`) may also be of interest to you.

Structural optimization with constraint forces has been not been benchmarked as much with larger systems, so please let us know if there are strange relaxations happening. 

3. Could you please share me a formal manual file of pycdft?
The *rst files are the build files for generating a manual for pycdft. You can generate *html files that can be viewed in your browser by installing sphinx; the instructions are in `<path_to_pycdft>/doc/docify.sh`. After installing sphinx, run the `docify.sh `script.

**Comment by Fly330** [comment]
Dear Dr. Wang,
Thank you for your great suggestions about construction of molecular fragments and structural optimization with constraint potential in the pycdft package. And according to the detailed PyCDFT manual, I tried constructing a simplified mode (Au-thiophene, a thiophene molecule with a gold atom in Fig.1) and calculating the energies of diabatic electronic states of the Au-thiophene model (Au-thiophene and Au-thiophene(-)). The Franck-Condon and relaxation processes of Au-thiophene(-) were considered.
![POSCAR](https://user-images.githubusercontent.com/21698419/142033457-0a761ab5-e5f4-41b0-8121-f682cb6719c9.png)
Fig.1 the structure of Au-thiophene model.

For Franck-Condon calculation,
the part of QboxDriver was written as “
sample=sample,
init_cmd=”load gs.xml\n”
        “set xc PBE\n”
        “set wf_dyn JD\n”
        “set scf_tol 1.0E-8\n”,
scf_cmd=”run 0 200 3”
“,

CDFTSolver part was written as “
job=”scf”, optimizer=”brenth”, sample=sample, dft_driver=qboxdriver, maxscf=800
“,

and ChargeConstraint part was written as “
sample=solver1.sample,
fragment=Fragment(solver1.sample,solver1.sample.atoms[1:10]), #ps: locating at thiophene frament
N0=27, #ps: one electron more than the sum of valence electrons of thiophene
N_top=1E-5
“.

For relaxation calculation with constraint potential,
the QboxDriver part was modified as “
...
init_cmd=”...”
        “set atoms_dyn CG\n”
        “set force_tol 1.0E-3\n”,
opt_cmd=”run 100 200 3”
“,

and CDFTSolver part was modified as “
job=”opt”, ..., maxstep=100, F_tol=1E-3
“.


However, the program prompted an assertion error “<class ‘AssertionError’>, AssertionError(), <traceback object at 0x2b3ebf0a41c0>” in the former calculation and the program blocked at QboxDriver part in the latter calculation. I don’t know what wrong is in the PyCDFT input files of both calculations. **Could you please teach me how to modify the input files in order to achieve the simulation of electronic states of Au-thiophene(-) in Franck-Condon and relaxation processes?** Many thanks!

To conveniently confirm, I have sent the input and output files of Au-thiophene, Au-thiophene(-) Franck-Condon and relaxation calculations in the attachment. 
[Au-thiophene.tar.gz](https://github.com/hema-ted/pycdft/files/7548466/Au-thiophene.tar.gz)
Due to the limit of storage, I deleted the ONCY files of elements and the output file, gs.xml.

Best Regards,
Yuan Fang

**Comment by Fly330** [comment]
Dear Dr. Wang,

I have solved the problems above!

For the Frank-Condon calculations, I set up the wrong the n1, n2, and n3 values in pycdft.common.sample class. Actually, the value should be obtained from the np2v variable in the output file of qbox pre-calculation. Once I set up the exact value (252 in this case), the scf calculation with constraint potential will start to run and converge.

For the geometry optimization calculations, except the wrong n1-3 values, I also set up the wrong variables in the pycdft.cdft and pycdft.dft_driver.qbox_driver class. After replacing solver1.solve_opt() to solver1.solve() (If I use the solver1.solve_opt(), the calculation will crash directly and report an error "core dumped") and adding the scf_cmd variable, the calculation can be run. However, the calculation stops and can't optimize the structure with constraint potential when the first scf calculation converges. **Could you please teach me how to modify the python input file to start the step of geometry optimization in pycdft? Many thanks!**

To conveniently confirm, I also sent the python input file of geometry optimization calculation in the attachment.

Best Regards,
Yuan Fang
[Au-thiophene.zip](https://github.com/hema-ted/pycdft/files/7689793/Au-thiophene.zip)

**Comment by Fly330** [comment]
Dear Dr. Wang,

Did you receive my messages above? Actually, I still look forward to extending the pycdft method  from qbox to the more common periodic DFT software, such as VASP or QuantumEspresso. Is it possible? And could you please teach me how to exactly use pycdft code in VASP or QuantumEspresso software? Many thanks!

Best regards,

Yuan Fang

**Comment by wwwennie** [comment]
Hi Yuan, 
For future reference, please open a new issue for a new question and close the old issue. This will help us keep track of issues.
Additionally, please follow standard practices in posting to forums for electronic structure codes (i.e., signing with your name and affiliation).

In answer to your last question, it is in principle possible to interface pycdft with other electronic structure codes. The other code would at minimum need to be able to take in external forces and external potentials, and a way to communicate with pycdft (this is the client-server mode for Qbox). You would also need to write a child class in dft_drivers for the code you specifically want and methods for parsing the charge density and wavefunction. 

I will try to get back to your other question but I will be delayed as the next couple of months will very busy for me.
